### ISSUE TITLE
Android Cloud Anchors ErrorNotAuthorized in .aab

### ISSUE THREAD

**Issue by WintorJesseVanBloemenhuis** [google-ar/arcore-unity-extensions#101]
We're having authentication issues with authentication using persistent cloud anchors. We get a ErrorNotAuthorized on hosting and resolving anchors. The issue only occurs when we publish (for internal testing) to the Google Play Console as .aab. It works as intended when building directly from Unity to the phone. This tells me our settings are correct, but something in the .aab build process is going wrong. The .apk from the Google Play Console > App bundle explorer also results in the same ErrorNotAuthorized.

We're using keyless authentication, I've checked the following:

- ARCore API is enabled
- OAuth client correct
- SHA1 is correct
- Package name is correct
- .aab is built with correct keystore enabled
- `ProjectSettings/AndroidResolverDependencies.xml` exists and `Temp/gradleOut/unityLibrary/build.gradle` contains entries with `com.google.android.gms` (from https://github.com/google-ar/arcore-unity-extensions/issues/22#issuecomment-880100863)

Unity 2020.3
ARFoundation 4.2.3
ARCore 4.2.3
ARKit 4.2.3
ARCore Extensions 1.33 (1.32 also doesn't work)

**Comment by devbridie** [comment]
Are you [using Play App Signing](https://support.google.com/googleplay/android-developer/answer/9842756?hl=en)? This will cause your app to be signed by a different key than the key you've used. See Register your App with [Register your app signing key with API providers](https://support.google.com/googleplay/android-developer/answer/9842756?hl=en#zippy=%2Capp-signing-process%2Cdescriptions-of-keys-artifacts-and-tools:~:text=Register%20your%20app%20signing%20key%20with%20API%20providers)

**Comment by WintorJesseVanBloemenhuis** [comment]
> Are you [using Play App Signing](https://support.google.com/googleplay/android-developer/answer/9842756?hl=en)? This will cause your app to be signed by a different key than the key you've used. See Register your App with [Register your app signing key with API providers](https://support.google.com/googleplay/android-developer/answer/9842756?hl=en#zippy=%2Capp-signing-process%2Cdescriptions-of-keys-artifacts-and-tools:~:text=Register%20your%20app%20signing%20key%20with%20API%20providers)

That's it, thank you so much. I did not know this was a thing!
