### ISSUE TITLE
Basic build fails when ran on Android device

### ISSUE THREAD

**Issue by vladtimug** [google-ar/arcore-unity-extensions#104]
When following [this google tutorial](https://codelabs.developers.google.com/arcore-unity-ar-foundation#1)  the app is built and deployed successfully but crashes at runtime on the android device without opening up the camera. Anyone came across this before?

**Comment by DevHexs** [comment]
Verify that the unity ARCore packages are from `4.1.x` and below, as this may be causing you compatibility problems.

**Comment by vladtimug** [comment]
I was able to fix this by changing the player settings so I will be closing it.
