### ISSUE TITLE
Geometry not working? (1.37)

### ISSUE THREAD

**Issue by mechpil0t** [google-ar/arcore-unity-extensions#121]
I am testing out the latest version of the Geospatial API and in the sample scene (Samples/ARCore Extensions/1.37.0/Geospatial Same/Scenes/Geospatial) there is a toggle for Geometry. However when I toggle it on nothing happens (no errors either). 

I added some debug logs to the geospatialcontroller.cs script, only the first is logged so I guess there nothing being added to the  _addedStreetscapeGeometrys or _updatedStreetscapeGeometrys

lines 675-715

`                if (_streetscapeGeometryVisibility)
                {
                    // get access to ARstreetscapeGeometries in ARStreetscapeGeometryManager
                    if (StreetscapeGeometryManager)
                    {
                        StreetscapeGeometryManager.StreetscapeGeometriesChanged
                            += (ARStreetscapeGeometrysChangedEventArgs) =>
                        {
                            _addedStreetscapeGeometrys =
                                ARStreetscapeGeometrysChangedEventArgs.Added;
                            _updatedStreetscapeGeometrys =
                                ARStreetscapeGeometrysChangedEventArgs.Updated;
                            _removedStreetscapeGeometrys =
                                ARStreetscapeGeometrysChangedEventArgs.Removed;
                        };
						Debug.Log("geo 1");
                    }

                    foreach (
                    ARStreetscapeGeometry streetscapegeometry in _addedStreetscapeGeometrys)
                    {
                        InstantiateRenderObject(streetscapegeometry);
						Debug.Log("geo 2");
                    }

                    foreach (
                        ARStreetscapeGeometry streetscapegeometry in _updatedStreetscapeGeometrys)
                    {
                        // This second call to instantiate is required if geometry is toggled on
                        // or off after the app has started.
                        InstantiateRenderObject(streetscapegeometry);
                        UpdateRenderObject(streetscapegeometry);
						Debug.Log("geo 3");
                    }

                    foreach (
                    ARStreetscapeGeometry streetscapegeometry in _removedStreetscapeGeometrys)
                    {
                        DestroyRenderObject(streetscapegeometry);
                    }
                }`

i have streetscape geometry enabled in the GeospatialConfig

is geometry only available in certain areas (we are in Tokyo)

**Comment by tkada** [comment]
I have same issue.
`ARStreetscapeGeometryManager.StreetscapeGeometriesChanged` event is not called.
I tried tokyo and yokohama in japan.

**Comment by mechpil0t** [comment]
fixed for me now

**Comment by tkada** [comment]
@mechpil0t 
How did you fix it?
What was the cause?

**Comment by mechpil0t** [comment]
i should clarify, there was a similar issue on the arcore gold demo. after they mentioned this fix the geometry started working for me on the standard sample - i rebuilt my app - not sure if that helped
https://github.com/google-ar/demo-megagolf/issues/1#issuecomment-1548873674
