### ISSUE TITLE
Streetscape Geometry API doesn't seem to be working properly in some regions

### ISSUE THREAD

**Issue by Eunji-new** [google-ar/arcore-unity-extensions#123]
I tested the GeoSpatial sample in an area that provides Google Street View and has VPS enabled.

However, the Streetscape Geometry API doesn't seem to be working properly. 
I didn't get a single mesh of the surrounding buildings.
Are there any areas where the Streetscape Geometry API does not work even in VPS-capable areas that provide street view?

All environment settings, such as setting GeospatialMode.Enabled, have been completed.

**Comment by 15kingben** [comment]
It is possible in certain locations for VPS to be Available but StreetscapeGeometry will not return any geometries.

Note that to receive streetscape geometries **both** [GeospatialMode.Enabled](https://developers.google.com/ar/reference/unity-arf/namespace/Google/XR/ARCoreExtensions#geospatialmode_enabled) and [StreetscapeGeometryMode.Enabled](https://developers.google.com/ar/reference/unity-arf/namespace/Google/XR/ARCoreExtensions#streetscapegeometrymode_enabled) must be set.

**Comment by Eunji-new** [comment]
@15kingben Thank you for the help. 
I set both GeospatialMode.Enabled and StreetscapeGeometryMode.Enabled. But I still can't see any geometries.
I think the area I am in is an area where VPS is available but StreetGeometry is not available.

**Comment by alamboley** [comment]
Same problem here.

**Comment by 15kingben** [comment]
Certain areas may have different levels of detail of Streetscape Geometry, and some areas will have no coverage. The coverage and quality of the streetscape geometry may vary by location, based on applicable laws.

**Comment by alamboley** [comment]
We tried at several locations in Paris without luck, @15kingben how can we know the coverage?

**Comment by 15kingben** [comment]
Hi Aymeric, Paris does have streetscape geometry coverage. If you are using the sample app, ensure your authentication settings are correct. If you are using another app, ensure that the config settings above are selected, and try logging the streetscape geometries returned to rule out a rendering issue.

This will not be robustly accurate, but if you want to get a sense of what areas around Paris will have streetscape geometry, you can try going to Maps in a desktop browser, and turning on satellite mode and Ctrl+clicking to pan down. If the area has 3D buildings it will likely also have Streetscape Geometry

**Comment by alamboley** [comment]
Ok we got an issue with URP, every material was pink and nothing displayed. It's ok now :)
