### ISSUE TITLE
New Build Issue in Android

### ISSUE THREAD

**Issue by divyashahVC** [google-ar/arcore-unity-extensions#128]
How to give the reference of new XR Origin (You have only use AR for the reference in unity inspector & even can't change it) for Mobiles in unity

**Comment by mrichards** [comment]
ARCore Extensions now supports ARF 5.x as of the 1.41 release. See our [migration guide](https://developers.google.com/ar/develop/unity-arf/update-to-ar-foundation-5) for details.
