### ISSUE TITLE
v1.38.0 source code is not available

### ISSUE THREAD

**Issue by KyryloKuzyk** [google-ar/arcore-unity-extensions#132]
Hi,

The latest version is 1.38.0, but its source code is not present in the git repository. 

I believe pressing the 'Push' button in version control should fix the issue :)

**Comment by voropserg** [comment]
You can get the source code from the release Assets. It is relevant.
With v1.38.0 HostAnchor/ResolveAnchor became depricated, so Samples is a good place to look for a Promise based hosting/resolving implementation

**Comment by KyryloKuzyk** [comment]
@voropserg Yes, I saw the source code in the Release section, thank you. 

The problem is that I'm offering a [custom fork](https://github.com/KyryloKuzyk/arcore-unity-extensions) of this repo to my customers and I would like to merge my fork with v1.38.0 using git.

**Comment by KyryloKuzyk** [comment]
Thank you!
https://github.com/google-ar/arcore-unity-extensions/commit/8c310cdc5796dccf9e0a5214143492a823e025bf
