### ISSUE TITLE
Builds fail when target platform is Windows.

### ISSUE THREAD

**Issue by RobinopdeBeek** [google-ar/arcore-unity-extensions#137]
I have a project that targets Android, iOS, Windows and Mac. The Windows and Mac builds of course don't use ARCore Extensions, so I have everything disabled in XR Plugin Management > ARCore Extensions. 

But when I try to make a build I get errors regarding missing types or namespaces. Probably because the target platform is not Android or iOS. 

Easy to reproduce:
1. Create a new project and import ARCore extensions.
2. Disable everything in XR Plugin Management > ARCore Extensions. 
3. switch platform to windows and build.
4. Errors received.

The errors received:
`Library\PackageCache\com.google.ar.core.arfoundation.extensions@8c310cdc57\Runtime\GeospatialCreatorRuntime\Scripts\Internal\ARGeospatialCreatorAnchor.cs(26,38): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Google.XR.ARCoreExtensions' (are you missing an assembly reference?)`

`Library\PackageCache\com.google.ar.core.arfoundation.extensions@8c310cdc57\Runtime\GeospatialCreatorRuntime\Scripts\Internal\ARGeospatialCreatorOrigin.cs(25,38): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Google.XR.ARCoreExtensions' (are you missing an assembly reference?)`

`Library\PackageCache\com.google.ar.core.arfoundation.extensions@8c310cdc57\Runtime\GeospatialCreatorRuntime\Scripts\Internal\ARGeospatialCreatorAnchor.cs(197,35): error CS0246: The type or namespace name 'ARGeospatialAnchor' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by RobinopdeBeek** [comment]
I just wanted to mention that this is blocking our development quite significantly, as we can't build to Windows anymore. And I also can't take out the ARCore Extensions package, because that would break our Android and iOS side. 

If you know a workaround that would be greatly appreciated :)

**Comment by devbridie** [comment]
Still looking into this in the general case, but as a stopgap solution, I think you should be able to wrap every offending file in 

```
#if !UNITY_STANDALONE_WIN
... ARF lines causing compilation failures
#endif
```

**Comment by RobinopdeBeek** [comment]
Unfortunately after wrapping the scripts as you mentioned it just went on to other errors. This time in our own code that implements ARCore Extensions. Seems like the ARCore Extensions package is only available when building for Android or iOS?

**Comment by RobinopdeBeek** [comment]
hmm... yes then I think it is my fault for still having everything in one big asmdef... The Windows part doesn't use any ARCore Extensions code, but would be best if it was separated with assemblies. Thanks

**Comment by RobinopdeBeek** [comment]
@devbridie After putting everything in correct assembly definitions it solved the issue with my own implementation code that uses ARCore Extensions. So that needed to be done.

However, the first errors I mentioned in the original issue still need to be solved. After looking at the asmdefs for ARCoreExtensions it's actually pretty clear and easy to solve. The **Google.XR.ARCoreExtensions.GeospatialCreator.asmdef** needs to use the same Platforms as **Google.XR.ARCoreExtensions.asmdef**. (Android, iOS and Editor) That would solve this issue.
![image](https://github.com/google-ar/arcore-unity-extensions/assets/31888353/6524d864-54e0-4a46-b46b-26979d011326)
![image](https://github.com/google-ar/arcore-unity-extensions/assets/31888353/070d074f-a8b7-4485-8b92-df4fd5c42662)
