### ISSUE TITLE
Capture full resolution camera image

### ISSUE THREAD

**Issue by lancefi** [google-ar/arcore-unity-extensions#14]
Any plans to let us capture a full resolution photo during an AR session (even paused)?

Can we or will we be able to use a shared camera session and the camera2 api?

I need to be able to use AR to guide the user in aligning the camera and then take a full resolution photo. Is this possible as of now? Or will it be possible at a later date?

**Comment by kcurry722** [comment]
[samsungsocial_gk000000891820_20200507_access.zip](https://github.com/google-ar/arcore-unity-extensions/files/4593159/samsungsocial_gk000000891820_20200507_access.zip)

**Comment by ZiadJ** [comment]
@lancefi It's been a while now and I'm wondering if you've been able to find a workaround for this issue.

**Comment by chiangandy** [comment]
Do you mean to do the screen capture on ARCore app?
If it is and you are using Unity, I just do this part recently.
in button action:
`
            string fileName = "womoshot"+generate_event_id()+".png";
            string filePath = Application.persistentDataPath + "/";   
            StartCoroutine(CaptureScreenshotWithCallback(filePath, fileName));
` 
then put code on that.
`
IEnumerator CaptureScreenshotWithCallback(string filePath, string fileName)
{
     ScreenCapture.CaptureScreenshot(filePath+fileName);
}
`

I hope this can answer your question.

**Comment by mrichards** [comment]
Hopefully the screenshot solution posted by @chiangandy meets your needs. ARCore does not offer an official way to do this, however, the camera image is a material on the background renderer and may be accessible that way.
