### ISSUE TITLE
API Call Limit for Geospacial Creator

### ISSUE THREAD

**Issue by DevLars-rookie** [google-ar/arcore-unity-extensions#159]
We have a request for an AR-Experience-App from a large customer where the Experience should take place
in a large football stadium in a narrow time window. So eventually serveral thousand people are using the app nearly
at the same time. Is this possible with the existing api limits for the geospacial creator? Could this limit be extended if the
customer pays for the request? Best regards Lars

**Comment by chankeiro** [comment]
I would also like to know if the limit can be extended.

**Comment by mrichards** [comment]
Hi folks, thanks for the question! You can request a temporary raise in the quota limit from Google Cloud Platform. Please refer to [this document](https://cloud.google.com/docs/quota/understand-limits) for instructions.
