### ISSUE TITLE
How to Use ARAnchorManager.AddAnchor(double, double, double, Quaternion)?

### ISSUE THREAD

**Issue by gtk2k** [google-ar/arcore-unity-extensions#166]
```
anchor = AnchorManager.AddAnchor(
    history.Latitude, history.Longitude, history.Altitude, eunRotation);
```
is used in GeospatialController.cs , but if you use this method elsewhere, it will be not found. How can I use this method?

**Comment by devbridie** [comment]
Hey,
ARAnchorManager.AddAnchor is an [extension method](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) on [`ARAnchorManager`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/api/UnityEngine.XR.ARFoundation.ARAnchorManager.html) defined in [`Google.XR.ARCoreExtensions.ARAnchorManagerExtensions`](https://developers.google.com/ar/reference/unity-arf/class/Google/XR/ARCoreExtensions/ARAnchorManagerExtensions#addanchor). Use `using Google.XR.ARCoreExtensions;` to get these extension methods!
