### ISSUE TITLE
Solf Reset without restarting the scene 

### ISSUE THREAD

**Issue by nitroman123** [google-ar/arcore-unity-extensions#169]
Is there i way to make a soft reset if case the scene if yours dont make a match with the real world ?

**Comment by mrichards** [comment]
Hi @nitroman123, please describe your question in more detail, specifically what you mean by "don't make a match with the real world". Are you having issues with localization or something else?

Generally there isn't a way to programmatically reset the ARCore components but you can close and reopen the entire Unity scene using the [`SceneManager` API](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.html).

**Comment by nitroman123** [comment]
Hi thanks for ansering , i am gonna give an example , lets say the user localization is not perfect when he is moving on and we dont want the scene to completely reasrt to lose all of his progress or accidently covering the phone camera and the scene doesnt localized well or keeps a tilt , a soft reset will be nice to counter effect this... 

A correct way of doing this will be nice

**Comment by 15kingben** [comment]
There is no way to induce ARCore to "reset" tracking, however ARCore will continuously update its estimate of device location, anchors and planes. For example if the camera is covered, the scene may drift, but after uncovering the camera tracking should eventually recover. Moving the device around more can help with this.

**Comment by nitroman123** [comment]
Thanks for the info , many times cause if read correctly there is a 68% chance of correct orientation , in our case many sites dont have VPS and a soft reset may be the solution in order to make it again

**Comment by 15kingben** [comment]
In locations without VPS coverage, latitude, longitude, altitude and orientation may not be accurate. The [accuracy](https://developers.google.com/ar/reference/unity-arf/struct/Google/XR/ARCoreExtensions/GeospatialPose#headingaccuracy) fields on GeospatialPose can help determine the current accuracy.

**Comment by nitroman123** [comment]
I know i read them but i noticed this behavior and this kind of progress will help , i opened many times the app from different locations and i saw that making it open and close the app from same spot sometimes if fine sometimes not...
