### ISSUE TITLE
Arcore Extensions XR-Origin / AR-Origin

### ISSUE THREAD

**Issue by sauer3d-thws** [google-ar/arcore-unity-extensions#172]
Hi together,

following the getting started tutorial I am running into issues with packages.
https://developers.google.com/ar/develop/unity-arf/getting-started-extensions
Using Unity2022.3.5f1 I use the arcore-extensions 1.41.0 from github URL:
https://github.com/google-ar/arcore-unity-extensions.git
This automatically installs:
AR Foundation 5.0.6 / ARKit XR  5.0.6 / AR Core 5.0.6

After that an error occurs: "Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'" because I don`t have IOS build support installed.
After deleting the "Google.IOSResolver.dll" files it seems to work.

But when I try to setup the scene with "AR Session" + "XR Origin" and "ARCore Extensions" the "XR Origin" is not accepted as Session Origin in the AR Core Extensions Script, because the old AR Origin from version 4.x has changed to XR Origin.

Do I have to delete the XR Session Origin Script and use the deprecated AR Session Origin?
Is there a way to get an older package version from arfoundation? Only 5.x is shown in package manager.

What am I missing?

Thanks a lot and best regards,
Stefan

**Comment by mgarate** [comment]
You have to add a flag to your project for the ARCoreExtensions to know that you're using AR Foundation 5. Go to Player settings > Player > Other Settings > Scripting Compilation > Scripting Define Symbols: Add ARCORE_USE_ARF_5

Once you do this, the script will allow you to add XROrigin as the Origin.

**Comment by sauer3d-thws** [comment]
Hi mgarate,
thanks a lot! It seems to work...
Is my rude solution to delete IOSresolver the way to go without IOS build support, or is there another solution? Simply ignore it?
Best regards! Stefan

**Comment by mgarate** [comment]
No problem and sorry, I can't help you with your iOS problem. I don't know the answer.

**Comment by sauer3d-thws** [comment]
Thanks a lot. At the end I simply ignored the problem and it worked anyway on android.
Best regards, Stefan

**Comment by mukiwalar** [comment]
Thanks a lot!!

**Comment by tpaslou** [comment]
After adding the flag a few errors appeared in the console.  You have to close the project and re open it and then everything works fine.

**Comment by mrichards** [comment]
This issue is believed to be fixed with the release of ARCore Extensions for AR Foundation version 1.45.0. This package separates the package into two versions, one compatible with AR Foundation 4 and AR Foundation 4. Please see [the Release Notes](https://github.com/google-ar/arcore-unity-extensions/releases/tag/1.45.0) for more detail.

Using the new version will probably resolve your problem as it addresses a few issues in our beta ARF5 support, but if it doesn’t, please reopen so I can take another look.

Thanks!
