### ISSUE TITLE
No active UnityEngine.XR.ARSubsystems when manually loading ARCore plugin provider

### ISSUE THREAD

**Issue by fourthedesign** [google-ar/arcore-unity-extensions#175]
Hello, 
I am trying to combine both Coardboard XR Plugin and ARCOre in the same application which leads me to manually switch between these plugin providers using XRGeneralSettings. Switching to Cardboard works well, but when switching to ARCore the subsystems are not initialized "Warn Unity No active UnityEngine.XR.ARSubsystems.... is available. Please ensure that a valid loader configuration exists in the XR project settings." for Plane, Raycast, Camera and input subsystems.  
It is worth mentioning that everything works perfectly if I have the "Initialize XR on Startup" checked in the XR Plugin Management Settings which leads me to believe that my scene setup is correct and the problem is in the way I load the plugin in my code.

I have tried different approaches such as 
1. Loading the plugin before the scene loading. I first loaded the plugin and then loaded the specific scene
2. Waiting for the initialization to be over using:
`   while (!XRGeneralSettings.Instance.Manager.isInitializationComplete)
        {
            yield return null;
        }`
3. Leaving only the ArCore plugin ticked in the XR plugin Management settings, so it 1st int he loaders list
4. Ensuring that Camera Permissions are granted and waiting if they are not
5. Reloading the AR elements on the scene using ARSession.reset, disabling and then enabling the AR elements when var startSuccess = m_SelectedXRLoader.Start(); has returned true
6. Instantiating the AR  scene (ArSession,Camera etc) after startSuccess has returned true. 

It looks like even though the m_SelectedXRLoader.Start() becomes true, the subsystems are never correctly initialized

I would greatly appreciate any help!

```
XRLoader m_SelectedXRLoader;
 private void Awake()
    {
        StartXR(0);
    }

 void StartXR(int loaderIndex)
    {
        Debug.Log("TestStartXR: " + loaderIndex);

        // Get the selected XR loader
        if (m_SelectedXRLoader == null)
        {
            Debug.Log("m_SelectedXRLoader== null");
            m_SelectedXRLoader = XRGeneralSettings.Instance.Manager.activeLoaders[loaderIndex];
        }

        Debug.Log("m_SelectedXRLoader: " + m_SelectedXRLoader.name);
        StartCoroutine(StartXRCoroutine());
    }

    IEnumerator StartXRCoroutine()
    {
        Debug.Log("Init XR loader");

        // Initialize the selected XR loader
        var initSuccess = m_SelectedXRLoader.Initialize();
        Debug.Log("initSuccess: " + initSuccess);
        if (!initSuccess)
        {
            Debug.LogError("Error initializing selected loader.");
        }
        else
        {
            yield return null;
            Debug.Log("Start XR loader");

            // Start the selected XR loader
            var startSuccess = m_SelectedXRLoader.Start();
            if (!startSuccess)
            {
                yield return null;
                Debug.LogError("Error starting selected loader.");
                m_SelectedXRLoader.Deinitialize();
            }

            Debug.Log("Starting subsystems");
            XRGeneralSettings.Instance.Manager.StartSubsystems();
        }
    }
```
   Android log for the code above:
![Screenshot_1](https://github.com/google-ar/arcore-unity-extensions/assets/99669150/2c953070-77bf-4c2e-99b7-f985929a8aaf)

**Comment by mrichards** [comment]
Hi @fourthedesign , ARCore does not currently support switching between XR plugins.  You may be able to get it to work but we do not have any advise to share on how to move forward.

I'd like to hear your use case. What are you trying to achieve with both subsystems?

**Comment by fourthedesign** [comment]
Hello @mrichards, 
Our goal is to have a unified application that allows users to choose between Cardboard and AR Core scenes. Activating and deactivating Cardboard subsystem was easy to achieve, but we did not manage to make AR Core work similarly no matter what we tried. If you don't have "Initialize XR on Startup" checked it does not work even if everything seems correct. 
As a temporary solution, we separated the 2 subsystems into 2 different applications that are connected using deep links. This is obviously not ideal but at least it works.
We would still like to know if someone has managed to achieve the described behavior since it is something that may be useful for a variety of projects.

**Comment by chankeiro** [comment]
Hi @fourthedesign . For me, using TrySetLoaders works. Something like this:
`
_xrManager = XRGeneralSettings.Instance.Manager;
List<XRLoader> xrLoadersList = new List<XRLoader>();
xrLoadersList.Add(_xrManager.activeLoaders.Where(loader => loader.name == "AR Core Loader").First());
if (!_xrManager.TrySetLoaders(xrLoadersList))
    Logging.OmigariHP("Couldn't Initialize XR Loaders");
else
{
    _xrManager.InitializeLoaderSync();
    _xrManager.StartSubsystems();
}
`

**Comment by mrichards** [comment]
@chankeiro & @fourthedesign Thank you both for sharing your solutions! Adding support for dynamically switching plugins is not on the roadmap currently but we'll consider it in the future if there's enough community interest.
