### ISSUE TITLE
Geospatial AR Oculus (How To)

### ISSUE THREAD

**Issue by DairexLord1** [google-ar/arcore-unity-extensions#176]
Hello
I am working on Oculus app and want to implement Geospatial into AR Oculus build

I am using Oculus OpenXR
Is there a way to run Geospatial with OpenXR for Oculus?

**Comment by mrichards** [comment]
Thanks for the question @DairexLord1 , unfortunately ARCore does not support Oculus at this time, so I do not expect you'll be able to get the Geospatial APIs to work on that platform.
