### ISSUE TITLE
ARGeospatialAnchor 

### ISSUE THREAD

**Issue by devnewverse** [google-ar/arcore-unity-extensions#177]
When I change the position of the ARGeospatialAnchor, the change is made but immediately returns to the original anchor position. How can I change the position of an ARGeospatialAnchor at runtime? (I only need to change the altitude)

i have:

` List<ARGeospatialAnchor> with all started anchor`
 
 and this to change:

```
for (int i = 0; i < anchors.Count; i++)
{
    Vector3 newPos = anchors[i].transform.position;
    newPos.y += altitude;

    anchors[i].transform.SetPositionAndRotation(newPos, Quaternion.identity);                
}

```

**Comment by devnewverse** [comment]
Yes, that's the solution I used, destroy them all and recreate. Taking advantage of your goodwill or that of someone in the know, could you tell me if ARCore updates the anchor position online or locally after creating the anchors? I mean, in my solution, people most likely won't have internet, so I would need to create the anchors and save them locally. Is that possible?

**Comment by maxcelar** [comment]
> Yes, that's the solution I used, destroy them all and recreate. Taking advantage of your goodwill or that of someone in the know, could you tell me if ARCore updates the anchor position online or locally after creating the anchors? I mean, in my solution, people most likely won't have internet, so I would need to create the anchors and save them locally. Is that possible?

You can't use Geospatial and Cloud Anchors without the internet. They both use Google's ARCore API to resolve their position.

**Comment by devnewverse** [comment]
> > Yes, that's the solution I used, destroy them all and recreate. Taking advantage of your goodwill or that of someone in the know, could you tell me if ARCore updates the anchor position online or locally after creating the anchors? I mean, in my solution, people most likely won't have internet, so I would need to create the anchors and save them locally. Is that possible?
> 
> You can't use Geospatial or Cloud Anchors without the internet. They both use Google's ARCore API to resolve their position.

That's very bad news for me, thanks for your attention!
