### ISSUE TITLE
Is the snow outside breaking my Geospatial AR app?

### ISSUE THREAD

**Issue by slim-sheady19** [google-ar/arcore-unity-extensions#178]
Hi there! I am the developer behind [St Ann's Church AR](https://devpost.com/software/st-ann-s-ar), submitted to the Immersive Geospatial Challenge.  I have returned to the project to improve it because an owner-operator of a local tour company wants to include it in an upcoming walking tour.  However, the app is broken - at runtime, the object I want to place is not placing itself at the anchor where I want it to (placing itself instead at what appears to be the XR Origin where my phone is).  I checked my Unity scene and cannot find anything wrong or missing.  Furthermore, the build that worked back in November no longer works either.  Which leads me to suspect the snow on the ground throwing off the Visual Positioning System, since the images captured for Street View never have snow in them.  Do you have any guidance for this?  I am really excited to have the app included on an educational tour of the neighbourhood.  Posting a screenshot of all the AR related objects in my scene in case that helps.
![geospatial_help](https://github.com/google-ar/arcore-unity-extensions/assets/58230539/c92d6558-c75d-4e17-b409-a80106ab48e4)

**Comment by 15kingben** [comment]
It's certainly possible that snow could disrupt the Visual Positioning Service, depending on how much snow there is. If the snow is covering or obscuring certain areas of high detail, VPS may not be able to match the surroundings against StreetView imagery. To rule out other problems, you may want to try localizing against a scene without so much snow (e.g. the face of a building or a plowed road) If that is successful, you could guide users to look around fully to localize before looking in the direction of the park.

**Comment by slim-sheady19** [comment]
@15kingben sorry for the late response, I only work on this in my free time.  I don't think the snow broke it in the end.
