### ISSUE TITLE
What causes VpsAvailability.ErrorInternal?

### ISSUE THREAD

**Issue by chankeiro** [google-ar/arcore-unity-extensions#184]
Hi,

In a recent event built with the geospatial api I've received several VPSAvailability.ErrorInternal. The description of this error in the documentation is "An internal error occurred while determining availability.", which leads me to think that they are caused by a punctual internal error in the Api services, but the fact that they were concentrated in just a few devices throwing the error several times (most likely the user trying to relaunch the experience error after error) leads me to think that it also depends on the device. Is this the case? Is there anything we can do to prevent or minimize this error on these devices? Or does it just mean that the API cannot be run on these devices (even if they have GPS for AR installed) and we need to explain this to the users so they stop trying?

Here is the list of devices, number of errors and time span from first to last error:
- Redmi Note 11S, Android 11: 5 errors in 8 minutes
- Oppo A91, Android 11: 6 errors in 7 minutes
- Reno 4Z 5G, Android 12: 3 errors in 2 minutes
- Realme C25Y, Android 11: 1 error

I have also received the GeospatialMode "FeatureSupported.Unsupported" error from other different devices, so I understand that they are not exactly the same. 

Thanks for your help

**Comment by 15kingben** [comment]
FeatureSupported.Unsupported should only appear when ARCore or a particular feature (such as Geospatial) is not supported on that specific device.

VPSAvailability.ErrorInternal indicates some internal error and could appear for a variety of reasons. Do you have any more debug info from the error?

Additionally, I am seeing that some of these devices, e.g. Oppo A91 are not supported by ARCore: https://developers.google.com/ar/devices. This may cause VPSAvailability.ErrorInternal if you are calling Geospatial methods on those unsupported devices. In your app, you should first check for ARCore support via [ARSession.CheckAvailability()](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARSession.html) and Geospatial support via [AREarthManager.IsGeospatialModeSupported()](https://developers.google.com/ar/reference/unity-arf/class/Google/XR/ARCoreExtensions/AREarthManager#isgeospatialmodesupported), and show an error to those users.

**Comment by chankeiro** [comment]
i @15kingben. Thanks for your reply. Unfortunately, I don't have any more debug data. These are user devices and I don't know who they are nor do I have access to them.

Yes, I noticed that some of them are not in the ARCore supported devices list. But before starting the scene, I always check if they have Google Play Services for AR installed, and I also check ARSession.CheckAvailability(), camera permissions, network connection, LocationServicesStatus, etc. before calling AREarthManager.CheckVpsAvailabilityAsync(). I do this in a similar way to the Unity Geospatial sample. And these devices pass all these checks, but still throw the VPSAvailability.ErrorInternal.

And yes, there is another group of (unsupported) devices, like a Moto G71 5G, that get a VpsAvailability.Available after all the checks, but later they still throw a FeatureSupported.Unsupported when calling EarthManager.IsGeospatialModeSupported(GeospatialMode.Enabled), so my guess is that this VpsAvailability.ErrorInternal is not related to the GeospatialMode being supported by the device.

I guess I just need to know if, after getting the VpsAvailability.ErrorInternal, is it safe to tell the user to stop trying because it will not work no matter how many times they try, or should I display a message asking to try again because this ErrorInternal can sometimes appear randomly.

**Comment by chankeiro** [comment]
Hi. Any recommendations regarding the last paragraph of my previous comment?

**Comment by 15kingben** [comment]
Hi @chankeiro, unfortunately ErrorInternal could be indicative of a number of errors and some of those could be transient. Unfortunately, I was not able to determine what the unifying cause in this case would be, but I think the best option would be to simply treat ErrorInternal as a retryable error, even though for certain devices that does not seem to be the case

**Comment by chankeiro** [comment]
Thanks for the answer, @15kingben . I'll do as you suggest.
