### ISSUE TITLE
Help - About the coming Harmony Next OS in this year , will Arcore support that OS ?

### ISSUE THREAD

**Issue by rere332** [google-ar/arcore-unity-extensions#193]
Hey,
 I understand that Harmony Next OS is set to be published in October of this year. 
Will Arcore support Harmony Next OS ? 
Could anybody please let me know if there are any plans to support this OS? It would be beneficial for us to have a clear understanding of the roadmap in order to align our development efforts accordingly.

https://en.wikipedia.org/wiki/HarmonyOS_NEXT

is there someone who can give the answer, thanks a lot.

**Comment by devbridie** [comment]
> The kernel of HarmonyOS NEXT does not include the compatibility layer of [AOSP](https://en.wikipedia.org/wiki/Android_(operating_system)) framework with Android libraries from [EMUI](https://en.wikipedia.org/wiki/EMUI) in the [user space](https://en.wikipedia.org/wiki/User_space_and_kernel_space) and cannot run Android [apk](https://en.wikipedia.org/wiki/Apk_(file_format)) apps natively
> [(source)](https://en.wikipedia.org/wiki/HarmonyOS_NEXT#History)

I'm not aware of any plans to support this operating system and it doesn't seem likely ARCore would work out of the box.

**Comment by rere332** [comment]
@devbridie  thank you for your reply!!!
Here is more info about our app, we are using Unity to build our app and in this Unity project we use Arcore as a plugin for Android platform. As HarmonyOS Next is coming ,we are worried that Arcore plugin may not work on HarmonyOS Next Platform. 
Any idea about this ?
