### ISSUE TITLE
PlayServicesResolver conflicts with Firebase one

### ISSUE THREAD

**Issue by alfiolocastro** [google-ar/arcore-unity-extensions#2]
Built in PlayServicesResolver conflicts with Firebase one.
I tried to delete the Firebase's one but I get some errors in firebase scripts

Trying to delete the one included in extensions package solved that error (I didn't compiled still so don't know if it works, I'll update this issue asap with results) 

How to replicate:
- install Firebase packages
- install arcore-unity-extensions

**Comment by pap3rinik** [comment]
I confirm that the workaround works.

**Comment by simplesab** [comment]
This conflict generates a replicable issue for me when building for iOS.
If I use the Firebase PlayServicesResolver (version 1.2.144) the iOS build works when starting it from XCode but is killed if I start it from the device. (the ios watchdog kills an app if it hangs for more than 20 seconds) It does not take 20 seconds to start from Xcode, and I tried it with a basic scene, but I get the same behaviour.

How to replicate:
• install arcore-unity-extensions
• install latest unity-jar-resolver: https://github.com/googlesamples/unity-jar-resolver
• remove unity-jar-resolver from arcore-unity-extensions
• build a basic scene for iOS
• try to run it directly from the iOS device

**Comment by mrichards** [comment]
Closing as obsolete as we believe the issue has been fixed with latest versions. Please open a new issue if a similar problem persists.
