### ISSUE TITLE
Question : Create GPS Anchor when app is running ?

### ISSUE THREAD

**Issue by NathalieTomas** [google-ar/arcore-unity-extensions#200]
Hello, I have a question regarding the use of Geospatial. We would like to develop an application that allows positioning 3D models anywhere based on GPS coordinates entered by the application's users. Therefore, we would like to do this outside of the Unity editor and create automatic anchors directly from the application. When we tried, we received a message indicating that it was not possible as this feature is only available in the editor. How can we achieve this?

**Comment by 15kingben** [comment]
Can you achieve this by [adding Geospatial Anchors](https://developers.google.com/ar/reference/unity-arf/class/Google/XR/ARCoreExtensions/ARAnchorManagerExtensions#addanchor) using lat/lng/alt and orientation values, or the corresponding methods for terrain/rooftop anchors?

**Comment by 15kingben** [comment]
Check out this thread for more information: https://github.com/google-ar/arcore-unity-extensions/issues/174
