### ISSUE TITLE
NullReferenceException when quit AR scene while using ARGeospatialAnchor

### ISSUE THREAD

**Issue by sgs-fan-jiashen** [google-ar/arcore-unity-extensions#205]
ARfoundation: Version 5.0.7
Apple ARKit XR Plugin: Version 5.0.7
Unity : 2021.3.31f1

when i quit AR scene it pops up the error below:

NullReferenceException: Object reference not set to an instance of an object.
 at Google.XR.ARCoreExtensions.ARGeospatialAnchor.OnDestroy () [0x00000] in <00000000000000000000000000000000>:0

how can i fix it

**Comment by sgs-fan-jiashen** [comment]
tried [https://github.com/google-ar/arcore-unity-extensions/pull/187](url) but doesn`t work

**Comment by mrichards** [comment]
I haven't seen this issue. Are you quitting the scene programmatically? Can you provide a code snippet that demonstrates?
