### ISSUE TITLE
Unable to change the ARCore API inside the Unity Editor.

### ISSUE THREAD

**Issue by Akash07-tester** [google-ar/arcore-unity-extensions#206]
Hello, I am getting this weird error where in, if I change the API key, it shows these errors. The application however builds, but doesn't work. Any ideas on why I am getting these errors?

Hello, this is that errors I am getting:

Error 1:

Element 'meta-data', android:name='com.google.android.ar.API_KEY', Attribute '{http://schemas.android.com/apk/res/android}value' has value 'xxxNEW-API-KEYxxx' isn't compatible with the previous setting 'xxxOLD-API-KEYxxx'.
UnityEngine.Debug:LogError (object)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger:MergeAttributes (System.Xml.Linq.XElement,System.Xml.Linq.XElement,System.Xml.Linq.XElement&) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:158)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger:MergeXElement (System.Xml.Linq.XElement,System.Xml.Linq.XElement) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:106)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger:MergeChildren (System.Xml.Linq.XElement,System.Xml.Linq.XElement,System.Xml.Linq.XElement&) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:177)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger:MergeXElement (System.Xml.Linq.XElement,System.Xml.Linq.XElement) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:109)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger:MergeChildren (System.Xml.Linq.XElement,System.Xml.Linq.XElement,System.Xml.Linq.XElement&) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:177)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger:MergeXElement (System.Xml.Linq.XElement,System.Xml.Linq.XElement) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:109)
Google.XR.ARCoreExtensions.Editor.Internal.CustomizedManifestInjection:GenerateCustomizedAndroidManifest (System.Xml.Linq.XDocument,Google.XR.ARCoreExtensions.Internal.ARCoreExtensionsProjectSettings) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/ModulesWorkflow/CustomizedManifestInjection.cs:73)
Google.XR.ARCoreExtensions.Editor.Internal.CustomizedManifestInjection:OnPostGenerateGradleAndroidProject (string) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/ModulesWorkflow/CustomizedManifestInjection.cs:91)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Error 2:
BuildFailedException: Element 'meta-data', android:name='com.google.android.ar.API_KEY', Attribute '{http://schemas.android.com/apk/res/android}value' has value 'xxxNEW-API-KEYxxx' isn't compatible with the previous setting 'xxxOLD-API-KEYxxx'.
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger.MergeAttributes (System.Xml.Linq.XElement element1, System.Xml.Linq.XElement element2, System.Xml.Linq.XElement& resultElement) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:159)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger.MergeXElement (System.Xml.Linq.XElement element1, System.Xml.Linq.XElement element2) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:106)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger.MergeChildren (System.Xml.Linq.XElement element1, System.Xml.Linq.XElement element2, System.Xml.Linq.XElement& resultElement) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:177)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger.MergeXElement (System.Xml.Linq.XElement element1, System.Xml.Linq.XElement element2) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:109)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger.MergeChildren (System.Xml.Linq.XElement element1, System.Xml.Linq.XElement element2, System.Xml.Linq.XElement& resultElement) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:177)
Google.XR.ARCoreExtensions.Editor.Internal.AndroidManifestMerger.MergeXElement (System.Xml.Linq.XElement element1, System.Xml.Linq.XElement element2) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/AndroidManifestMerger.cs:109)
Google.XR.ARCoreExtensions.Editor.Internal.CustomizedManifestInjection.GenerateCustomizedAndroidManifest (System.Xml.Linq.XDocument manifestDoc, Google.XR.ARCoreExtensions.Internal.ARCoreExtensionsProjectSettings settings) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/ModulesWorkflow/CustomizedManifestInjection.cs:73)
Google.XR.ARCoreExtensions.Editor.Internal.CustomizedManifestInjection.OnPostGenerateGradleAndroidProject (System.String path) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@e4aa1134b129/Editor/Scripts/Internal/ModulesWorkflow/CustomizedManifestInjection.cs:91)
UnityEditor.Android.AndroidBuildPipelineInterfaces.OnGeneratePlatformProjectPostprocess (System.String path, System.Boolean strict) (at <5f40cdb07bd44d76a23dad985a4ec283>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

![Screenshot 2024-06-26 224144](https://github.com/google-ar/arcore-unity-extensions/assets/174586681/496acca1-6044-4d70-a6c4-14112dc880a4)

**Comment by devbridie** [comment]
Unfortunately this is a known issue with some remnants of old build artifacts. Could you try a clean build and see if that resolves it for now?

![image](https://github.com/google-ar/arcore-unity-extensions/assets/442644/8ba51b45-993b-4d48-956e-35cd5f9c146c)

**Comment by Akash07-tester** [comment]
Thanks!! This solves the issue.
