### ISSUE TITLE
Using Scene Semantic API and Geospatial API in same project is not working Scene Semantic API when user denied location permission.

### ISSUE THREAD

**Issue by ForJobOk** [google-ar/arcore-unity-extensions#208]
I faced problem using Scene Semantic API and Geospatial API in same Unity project.

My app has two scenes, one using Scene Semantic API and one using Geospatial API.

If user play the scene that uses only Scene Semantic API, but it does't start the segmentation when user denied permission of location.

As far as I can see from the log, it fails as of [CreateARCoreSession](https://github.com/google-ar/arcore-unity-extensions/blob/09f3de423232cb087ab450f72a2ec56eedd9c465/Runtime/Scripts/Internal/IOSSupportManager.cs#L157) regarding permissions.

`Error log`
> Failed to configure the session with error: ErrorLocationPermissionNotGranted.

I think we should only require permissions for the APIs that our users are using.

What is your opinion？

## Version
Unity 2022.3.24f1
ARCore Extensions 1.42.0
AR Foundation 5.1.3

**Comment by swardle** [comment]
I looked at ARCoreExtensions.cs I see we are calling module.GetRuntimePermissions(_cachedConfig);  I think this should do what you want. Unless we have a bug. 

Do you have 2 ARCoreExtensionsConfig objects? If not I think if you create 2 different ones for each scene then you can do what you are trying to do.

I agreed you need to enable the Geospatial in ProjectSetting->Xr-Plugin Management->ArCore Extensions for your whole project. But I don't think the user should asked if your ARCoreExtensionsConfig disabled Geospatial and enabled Semantics for example.  If this is not the case can you send me an example project? 

In a little more details  you will need a ARCore Extensions object in your scene that points to the right ARCoreExtensionsConfig like this one from Persistent Cloud Anchor sample. 

<img width="714" alt="AR_Core_Extensions_object" src="https://github.com/user-attachments/assets/ee1c18de-7af1-485e-81aa-7a33360c0686">

That points to this config. 

<img width="913" alt="AR_Core_Extensions_config" src="https://github.com/user-attachments/assets/8373c1b6-5c81-46b0-a435-cdace4decbe7">

If you have scenes setup with both of these... humm not sure what is happening here and I would love to get project that showed me what you are doing as I think this should work.

**Comment by ForJobOk** [comment]
Thank you for your quick response.

You're right. I misunderstood how to use the config.
I thought the config was the same as ARCoreExtenstions in the project settings, but it's not.

**Comment by devbridie** [comment]
Happy to hear this helped!
