### ISSUE TITLE
XR Origin not recognized in the ARCoreExtensions selection

### ISSUE THREAD

**Issue by reefbreak** [google-ar/arcore-unity-extensions#213]
Setting up a scene to use ARCore Extensions, unable to select the XROrigin in the scene for the AR Session Origin, all other fields can be selected correctly, screenshot attached.

Versions in Use - Unity 2022.3.42
ARCoreExtensions 1.45
ARRoundation 5.1.5
ARCore/ARKit 4.1.5

![image](https://github.com/user-attachments/assets/6d66270b-d29b-4579-8fe5-ec0e2cee2f0a)

**Comment by reefbreak** [comment]
Resolution actions : I've gone back to v1.44 and added back the ARCORE_USE_ARF_5 directive.

**Comment by swardle** [comment]
Which version of ARCore Extensions for AR Foundation 1.45 are you using?

Before 1.45 the prototype AR Foundation 5 suport we used defines like ARCORE_USE_ARF_5 however now there are 2 versions. See the release of the Unity package tgz on github here:

https://github.com/google-ar/arcore-unity-extensions/releases/tag/1.45.0

You can see there are 2 packages now:
- arcore-unity-extensions-1.45.0-arf4.tgz
- arcore-unity-extensions-1.45.0-arf5.tgz

Given your problems I think you are using the AR Foundation 4 (ARF 4) version but you want to use the AR Foundation 5 (ARF 5) one. Tell me if I have this wrong. 

The new ARCore Extensions for ARF5 package should make it easy to run ARCore samples out of the box with out defines like ARCORE_USE_ARF_5.  This fixed the bugs in our samples where XR Origin on our ARF 5 scenes was null.

**Comment by reefbreak** [comment]
I think you're right, I started from scratch and using the following link :
https://github.com/google-ar/arcore-unity-extensions.git#arf5

Per the instructions here - 
https://developers.google.com/ar/develop/unity-arf/getting-started-extensions?ar_foundations_version=5

Has worked with a windows unity build 2022.3.43
