### ISSUE TITLE
How can I check LOD before using Streetscape Geometry API?

### ISSUE THREAD

**Issue by ForJobOk** [google-ar/arcore-unity-extensions#221]
I came across some information suggesting that enabling the terrain layer on Google Maps and panning down allows users to preview the presence of 3D buildings, potentially indicating the availability of Streetscape Geometry data in that location. 
https://github.com/google-ar/arcore-unity-extensions/issues/196

However, it seems that in the Google Maps web version, it isn’t possible to pan down terrain layers.

Given this limitation, could you advise if there is a reliable way to check which LOD (Level of Detail) is available for a specific area before making a request to the Streetscape Geometry API?

**Comment by 15kingben** [comment]
Hi @ForJobOk, my comment on https://github.com/google-ar/arcore-unity-extensions/issues/196 was incorrect, in the layers map it should be Map Type - Satellite to pan down and see 3D buildings, not Terrain. Areas with 3D buildings will likely have LOD 2, while other areas may have LOD 1 or no available geometry.

**Comment by ForJobOk** [comment]
Thank you for your response.
