### ISSUE TITLE
"Waiting for sufficient mapping quality" Cloud Anchor Stuck

### ISSUE THREAD

**Issue by AyazSaduken** [google-ar/arcore-unity-extensions#226]
Hi! I tried running cloud anchor sample project and after going to the HOST page and setting the object to scan - I get stuck on “waiting sufficient mapping quality”. This message holds for more than 5-10 minutes. At the same time I move and scan from all sides and very carefully. Tried 6 times, different objects and locations. I can't go any further than this message, it's always there.

I am using Unity 6, AR Foundation 6 and Keyless method. No other errors have occurred
![image](https://github.com/user-attachments/assets/7a8c20d2-9e50-4400-9a1b-7e9bb8f358e0)

**Comment by snowyao** [comment]
Same here, we have tested several devices, and EstimateFeatureMapQualityForHosting returns insufficient all the time no matter how we scan world environment

**Comment by AyazSaduken** [comment]
> Same here, we have tested several devices, and EstimateFeatureMapQualityForHosting returns insufficient all the time no matter how we scan world environment

In my case there are no other messages, that is, not even a mention that the quality of the scan is poor. Only “waiting for sufficient mapping quality”. This suggests that the values are not being passed somewhere.

**Comment by AyazSaduken** [comment]
SOLVED
For anyone facing a similar problem. If you hang on “Waiting for sufficient mapping quality”, you need to bind a camera with XROrigin for MainCamera. In XROrigin the camera is under CameraOffset and therefore it cannot detect it. You need to bind it in the ArCoreExtensionController script in the MainCamera value. This problem is caused by the new ARFoundation

For those who constantly return “insufficient” value when scanning. Try to change the location to a well-lit one and scan from above the object, above the object

**Comment by CisDutchRose** [comment]
Hey sorry to make this active again. But I have the same issue. On Android it doesn't work. The beans stay red. But on IOS they turn green. I use ersistentCloudAnchorsArf4 and Unity 6.4

Edit: Resolving on IOS is not working
