### ISSUE TITLE
Build on iOS

### ISSUE THREAD

**Issue by DMurzNN** [google-ar/arcore-unity-extensions#38]
1. Build XCode project
2. pod update
3. Open .xcworkspace
4. Buid and run on phone
5. Scan or Resolve -> Error Not Autorized
6. In XCode console error with FireBase, (FireBase app in console configure)
7. All OAuth clients configure and GoogleService-Info.plist paste in project
Android app work

**Comment by Jickelsen** [comment]
I seem to have the same issue on iOS. However, as a followup I get

`Returning home for reason: ARCore encountered an error state CheckingAvailability. Please start the app again.`

I see very little in the documentation regarding Firebase, so perhaps it is unrelated and I have something more fundamental keeping ARCore from running.

**Comment by DMurzNN** [comment]
I found working solution
https://developers.google.com/ar/develop/unity-arf/cloud-anchors/developer-guide-ios?hl=ca
