### ISSUE TITLE
Runtime Config - NullReferenceException

### ISSUE THREAD

**Issue by Saicopate** [google-ar/arcore-unity-extensions#44]
I am getting this while building for iOS:

`NullReferenceException: Object reference not set to an instance of an object
Google.XR.ARCoreExtensions.Internal.RuntimeConfig+<>c.<UploadInstance>b__7_0 (UnityEngine.Object x) (at package/Runtime/Scripts/Internal/RuntimeConfig.cs:79)
System.Collections.Generic.List`1[T].RemoveAll (System.Predicate`1[T] match) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Google.XR.ARCoreExtensions.Internal.RuntimeConfig.UploadInstance () (at package/Runtime/Scripts/Internal/RuntimeConfig.cs:79)`

Of course it cancels the build process. 
Any advice on how to handle this appreciated.

Unity 2021.1.7f, all AR packages at 4.1.7

**Comment by Saicopate** [comment]
Ok, I got it working with a solution from pull requests.

Anyway I find it sad that such an important and needed plugin is so poorly documented and has no support here.

**Comment by mihirterna** [comment]
Hi @Saicopate ,
Can you please update what was the solution for it ? Thanks.

**Comment by devbridie** [comment]
A fix for this is in #32 and will be resolved in the next release.
