### ISSUE TITLE
Any plan to upgrade to ARFoundation 3.1.0?

### ISSUE THREAD

**Issue by alfiolocastro** [google-ar/arcore-unity-extensions#6]
Actally this is incompatible with ARFoundation 3.x
Since this repo look quite inactive, do you have plans to supporting recent ARFoundations?

**Comment by DimitrisMar** [comment]
I am facing probably the same issue because of the change from Reference Points to Anchors.Is there something that we can do about that?

**Comment by pap3rinik** [comment]
any workaround out there?

**Comment by nothingAD** [comment]
+1 from me! Would be nice to use CloudAnchors with ARFoundation 3.x

**Comment by FDDdan** [comment]
I forked and replaced the Reference Points to Anchors. I didn't test it thoroughly, but it worked with the sample scenes and our test scenes. You can reference my fork in the PackageManager or directly in your manifest.json.
https://github.com/FDDdan/arcore-unity-extensions.git

**Comment by pap3rinik** [comment]
> I forked and replaced the Reference Points to Anchors. I didn't test it thoroughly, but it worked with the sample scenes and our test scenes. You can reference my fork in the PackageManager or directly in your manifest.json.
> https://github.com/FDDdan/arcore-unity-extensions.git

HERO!

**Comment by 15kingben** [comment]
ARCore now supports up to ARFoundation 5. See https://github.com/google-ar/arcore-unity-extensions/releases/tag/1.41.0 for details
