### ISSUE TITLE
Can't resolve cloud anchors between iOS and Android devices

### ISSUE THREAD

**Issue by futuyao** [google-ar/arcore-unity-extensions#7]
Issues: 

I'm trying to resolve on an iOS device a cloud anchor hosted by an Android device (or hosted on iOS and resolving on Android), the cloud anchor is not resolved correctly, and throw error "`ErrorResolvingPackageTooNew`" or "`ErrorResolvingPackageTooOld`". The Android device always throws error "`ErrorResolvingPackageTooOld`", and the iOS device always throws error "`ErrorResolvingPackageTooNew`", regardless of which device is the host.

Versions:
- ARCore Extension 1.14.0
- ARFoundation 2.1.3
- ARCore XR Plugin 2.1.1
- ARKit XR Plugin 2.1.2
- AR Subsystems 2.1.1
- Unity 2019.3.0f3

**Comment by tedruxpin** [comment]
Hello futuyao, we have resolved this in our upcoming release. In the meantime, you should be able to resolve the issue by copying an updated version of the arcore_client.aar file from our standalone SDK.
From:
https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Plugins/arcore_client.aar
To:
https://github.com/google-ar/arcore-unity-extensions/tree/master/Runtime/Plugins

Feel free to reopen this issue if that doesn't solve the problem.

**Comment by fredsa** [comment]
Leaving the issue open for now (to make it easier to find and reference). Once the release that fixes this is out, we'll close the issue.
