### ISSUE TITLE
Framework not found FBLPromises Error when using Xcode export

### ISSUE THREAD

**Issue by awarvrcode** [google-ar/arcore-unity-extensions#73]
I have the problem "Framework not found FBLPromises" Error when using Xcode to build.  
I found the problem caused  by installing the package "ARCore Extensions for AR Foundation". 
Even if I create an empty scene to build. It occurred the same problem.

**Comment by awarvrcode** [comment]
Solved it! Thank you!

**Comment by berkyonca** [comment]
> I encountered the same. In my case it was simply a matter of opening the .xcworkspace file instead of the .xcodeproj file and building from that Xcode Workspace.

This man is a genius ! Ty very much

**Comment by Gagas3110** [comment]
> I encountered the same. In my case it was simply a matter of opening the .xcworkspace file instead of the .xcodeproj file and building from that Xcode Workspace.

whutttt? really? i will try it. Thanks man !

**Comment by ramankanabi** [comment]
> I encountered the same. In my case it was simply a matter of opening the .xcworkspace file instead of the .xcodeproj file and building from that Xcode Workspace.

Thankkkk yoooouuuuuuuuuuuuu
