### ISSUE TITLE
IOS token authorization : ErrorNotAuthorized

### ISSUE THREAD

**Issue by voropserg** [google-ar/arcore-unity-extensions#92]
I'm not abel to host/resolve anchors using the signed JWT token. I'm using the latest stable version of Unity and recomended AR Foundation version. I had this problem on v1.31.0 and updating to v1.33.0 did not solve it. I did change the audience claim and followed the official IOS developer guide.  Looking into the logs and metrics of the Cloud Project  i didn't see any `google.geo.ar.v1.LocalizeService.StartSession` calls, similar to #87. The issues is most likely not with the token itself, I've compared it to the token of another working project and it was the same (excluding account names). Can it be a restriction of some sort in the Google Cloud project ?
For the record i'm hosting anchors with `arAnchorManager.HostAnchor(anchor, 365)` method.

**Comment by Barokoli** [comment]
I am able to host and resolve persistent cloud anchors with v1.33.0. My experiences in the cloud project are that there is different api calls for the geospatial system and for the persistent cloud anchors. 
Calls to the persistent cloud anchor api seem to be in the "google.arcorecloudanchor.v1beta2.CloudAnchorService" domain.
Calls to the geospatial system seem to be in the "google.geo.ar.v1.LocalizeService" domain.
For persistent cloud anchors in particular i get "google.arcorecloudanchor.v1beta2.CloudAnchorService.CreateAnchor", "google.arcorecloudanchor.v1beta2.CloudAnchorService.GetAnchor", "google.arcorecloudanchor.v1beta2.CloudAnchorService.ResolveAnchorAndLocalize".
So I think it shouldn't call "google.geo.ar.v1.LocalizeService.StartSession" when you only use persistent cloud anchors.

Are you sure your JWT token is correct? My token looks something like this when decoding with (https://jwt.io/):
{
  "iss": "cloudserviceaccountmail",
  "sub": "cloudserviceaccountmail",
  "iat": 1663765624,
  "exp": 1663769224,
  "aud": "https://arcore.googleapis.com/",
  "uid": "MSnR7Feb3rDNMDVMrNdm2SS532rsEW"
}

**Comment by deepakrhtsdev** [comment]
Hi Barokoli, I'm facing same issue that host anchor not working with JWT Token.
could you check my JWT token is correct or not?, getting below details when decoding

{
        "iss": "arcore-service@<my-project-name-some-number>.iam.gserviceaccount.com",
        "sub": "arcore-service@<my-project-name-some-number>.iam.gserviceaccount.com",
        "iat": 1677750970,
        "exp": 1680342970,
        "aud": "https://arcorecloudanchor.googleapis.com"
    }

**Comment by Barokoli** [comment]
With the new Endpoint you need "https://arcore.googleapis.com/" as the audience (aud)

**Comment by deepakrhtsdev** [comment]
@Barokoli, I changed the aud endpoint, and still getting call in session(_ session: GARSession, didFailToHost anchor: GARAnchor) method, when i initialise the GARSession with api key then it's working fine, but not with JWT Token 

"jwt_auth": {
        "iss": "arcore-service@memento-maps-374611.iam.gserviceaccount.com",
        "sub": "arcore-service@memento-maps-374611.iam.gserviceaccount.com",
        "iat": 1677817318,
        "exp": 1680409318,
        "aud": "https://arcore.googleapis.com/"
    }

**Comment by deepakrhtsdev** [comment]
Hi @voropserg, is resolved your issue?, now working fine hosting anchors with arAnchorManager.HostAnchor(anchor, 365) method?

if working fine at your end, let me know the process of create JWT Token and other things also!, it might help me to resolved my issue!

Thanks in advance!

**Comment by voropserg** [comment]
If anyone is still wandering, the issue i had was due to the incorrect `exp` value in the jwt token.
It **has** to be `iat + 3600` (1 hour)
Previously the documentation stated that you can set any `exp` you want and a 1 hour expiration time was recomended. The wording is changed now.
Make sure to set the correct values described on https://developers.google.com/ar/develop/unity-arf/cloud-anchors/developer-guide-ios
